teste/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :filmes
  resources :classis
  resources :cats
  devise_for :users
  resources :home 

  root to: 'home#index'
  get 'carts/show'
  get "/home/:id" => "home#show"
  get "/cat/:id" => "home#cat"
  get "/carrinho" => "cart#card"
  post '/add_to_cart/:id' => 'cart#add_to_cart', :as => 'add_to_cart'
  post '/remove_to_cart/:id' => 'cart#remove_to_cart', :as => 'remove_to_cart'
  get "/deslogar" => "user#logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

teste/app/models/classi.rb
class Classi < ApplicationRecord
	has_many :filmes
end

teste/app/controllers/classis_controller.rb
class ClassisController < ApplicationController
  before_action :set_classi, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /classis
  # GET /classis.json
  def index
    @classis = Classi.all
    @cats = Cat.all
  end

  # GET /classis/1
  # GET /classis/1.json
  def show
    @cats = Cat.all
  end

  # GET /classis/new
  def new
    @classi = Classi.new
    @cats = Cat.all
  end

  # GET /classis/1/edit
  def edit
  end

  # POST /classis
  # POST /classis.json
  def create
    @classi = Classi.new(classi_params)
    @cats = Cat.all

    respond_to do |format|
      if @classi.save
        format.html { redirect_to @classi, notice: 'Classi was successfully created.' }
        format.json { render :show, status: :created, location: @classi }
      else
        format.html { render :new }
        format.json { render json: @classi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classis/1
  # PATCH/PUT /classis/1.json
  def update
    respond_to do |format|
      if @classi.update(classi_params)
        format.html { redirect_to @classi, notice: 'Classi was successfully updated.' }
        format.json { render :show, status: :ok, location: @classi }
      else
        format.html { render :edit }
        format.json { render json: @classi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classis/1
  # DELETE /classis/1.json
  def destroy
    @cats = Cat.all
    @classi.destroy
    respond_to do |format|
      format.html { redirect_to classis_url, notice: 'Classi was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classi
      @classi = Classi.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classi_params
      params.require(:classi).permit(:nome)
    end
end

teste/app/helpers/classis_helper.rb
module ClassisHelper
end

teste/app/views/classis/_form.html.erb
<%= form_for @classi, :html => { :class => "form-horizontal classi" } do |f| %>

  <% if @classi.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@classi.errors.count, "error") %> prohibited this classi from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @classi.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                classis_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

teste/app/views/classis/edit.html.erb
<%- model_class = Classi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

teste/app/views/classis/index.html.erb
<%- model_class = Classi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @classis.each do |classi| %>
      <tr>
        <td><%= link_to classi.id, classi_path(classi) %></td>
        <td><%= classi.nome %></td>
        <td><%=l classi.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      classi_path(classi), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_classi_path(classi), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      classi_path(classi),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_classi_path,
            :class => 'btn btn-primary' %>

teste/app/views/classis/new.html.erb
<%- model_class = Classi -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

teste/app/views/classis/show.html.erb
<%- model_class = Classi -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @classi.nome %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              classis_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_classi_path(@classi), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              classi_path(@classi),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>