teste/config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :filmes
  resources :classis
  resources :cats
  devise_for :users
  resources :home 

  root to: 'home#index'
  get 'carts/show'
  get "/home/:id" => "home#show"
  get "/cat/:id" => "home#cat"
  get "/carrinho" => "cart#card"
  post '/add_to_cart/:id' => 'cart#add_to_cart', :as => 'add_to_cart'
  post '/remove_to_cart/:id' => 'cart#remove_to_cart', :as => 'remove_to_cart'
  get "/deslogar" => "user#logout"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

teste/app/models/cat.rb
class Cat < ApplicationRecord
    has_many :filmes
end

teste/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:nome)
    end
end

teste/app/helpers/cats_helper.rb
module CatsHelper
end

teste/app/views/cats/_form.html.erb
<%= form_for @cat, :html => { :class => "form-horizontal cat" } do |f| %>

  <% if @cat.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                cats_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

teste/app/views/cats/edit.html.erb
<%- model_class = Cat -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

teste/app/views/cats/index.html.erb
<%- model_class = Cat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= link_to cat.id, cat_path(cat) %></td>
        <td><%= cat.nome %></td>
        <td><%=l cat.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      cat_path(cat), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cat_path(cat), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cat_path(cat),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cat_path,
            :class => 'btn btn-primary' %>

teste/app/views/cats/new.html.erb
<%- model_class = Cat -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

teste/app/views/cats/show.html.erb
<%- model_class = Cat -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cat.nome %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              cats_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cat_path(@cat), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cat_path(@cat),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>